package com.solucionesweb.tags;

import javax.servlet.jsp.tagext.*;

public class ListaClienteCotizacionArticulosTagExtraInfo extends TagExtraInfo {
  public VariableInfo[] getVariableInfo(TagData data) {
    return new VariableInfo[] {
      new VariableInfo("idPluVar", "java.lang.String", true,
                       VariableInfo.NESTED),
      new VariableInfo("strIdReferenciaVar", "java.lang.String", true,
                       VariableInfo.NESTED),
      new VariableInfo("nombrePluVar", "java.lang.String", true,
                       VariableInfo.NESTED),
      new VariableInfo("cantidadVar", "java.lang.String", true,
                       VariableInfo.NESTED),
      new VariableInfo("vrVentaUnitarioVar", "java.lang.String", true,
                       VariableInfo.NESTED),
      new VariableInfo("vrVentaSinIvaVar", "java.lang.String", true,
                       VariableInfo.NESTED),
      new VariableInfo("vrVentaConIvaVar", "java.lang.String", true,
                       VariableInfo.NESTED),
      new VariableInfo("nombreLineaVar", "java.lang.String", true,
                       VariableInfo.NESTED),
      new VariableInfo("nombreSublineaVar", "java.lang.String", true,
                       VariableInfo.NESTED),
      new VariableInfo("marcaArteClienteVar", "java.lang.String", true,
                       VariableInfo.NESTED),
      new VariableInfo("nombreArchivoVar", "java.lang.String", true,
                       VariableInfo.NESTED),
      new VariableInfo("referenciaClienteVar", "java.lang.String", true,
                       VariableInfo.NESTED),
      new VariableInfo("comentarioVar", "java.lang.String", true,
                       VariableInfo.NESTED),
      new VariableInfo("itemVar", "java.lang.String", true,
                       VariableInfo.NESTED),
      new VariableInfo("idEstadoTxVar", "java.lang.String", true,
                       VariableInfo.NESTED),
      new VariableInfo("nombreUnidadMedidaVar", "java.lang.String", true,
                       VariableInfo.NESTED),
      new VariableInfo("nombreMarcaVar", "java.lang.String", true,
                       VariableInfo.NESTED),
      new VariableInfo("nombreCategoriaVar", "java.lang.String", true,
                       VariableInfo.NESTED),
      new VariableInfo("vrCostoVar", "java.lang.String", true,
                       VariableInfo.NESTED),
      new VariableInfo("vrCostoActualVar", "java.lang.String", true,
                       VariableInfo.NESTED),
      new VariableInfo("incrementoCostoVar", "java.lang.String", true,
                       VariableInfo.NESTED),
      new VariableInfo("vrCostoConIvaVar", "java.lang.String", true,
                       VariableInfo.NESTED),
      new VariableInfo("existenciaVar", "java.lang.String", true,
                       VariableInfo.NESTED),
      new VariableInfo("porcentajeDsctoVar", "java.lang.String", true,
                       VariableInfo.NESTED),
      new VariableInfo("vrVentaSinDsctoDf0Var", "java.lang.String", true,
                       VariableInfo.NESTED),
      new VariableInfo("letraDetalleInventarioVar", "java.lang.String", true,
                       VariableInfo.NESTED),
    };
  }
}