package com.solucionesweb.tags;

import javax.servlet.jsp.tagext.*;

public class ListaInventarioPluTagExtraInfo extends TagExtraInfo {
  public VariableInfo[] getVariableInfo(TagData data) {
    return new VariableInfo[] {
      new VariableInfo("idPluVar", "java.lang.String", true,
                       VariableInfo.NESTED),
      new VariableInfo("nombrePluVar", "java.lang.String", true,
                       VariableInfo.NESTED),
      new VariableInfo("vrGeneralVar", "java.lang.String", true,
                       VariableInfo.NESTED),
      new VariableInfo("vrMayoristaVar", "java.lang.String", true,
                       VariableInfo.NESTED),
      new VariableInfo("porcentajeIvaVar", "java.lang.String", true,
                       VariableInfo.NESTED),
      new VariableInfo("idTipoVar", "java.lang.String", true,
                       VariableInfo.NESTED),
      new VariableInfo("idLineaVar", "java.lang.String", true,
                       VariableInfo.NESTED),
      new VariableInfo("idUCompraVar", "java.lang.String", true,
                       VariableInfo.NESTED),
      new VariableInfo("idUVentaVar", "java.lang.String", true,
                       VariableInfo.NESTED),
      new VariableInfo("vrCostoVar", "java.lang.String", true,
                       VariableInfo.NESTED),
      new VariableInfo("vrCostoINDVar", "java.lang.String", true,
                       VariableInfo.NESTED),
      new VariableInfo("idCategoriaVar", "java.lang.String", true,
                       VariableInfo.NESTED),
      new VariableInfo("idMarcaVar", "java.lang.String", true,
                       VariableInfo.NESTED),
      new VariableInfo("vrSucursalVar", "java.lang.String", true,
                       VariableInfo.NESTED),
      new VariableInfo("factorVentaVar", "java.lang.String", true,
                       VariableInfo.NESTED),
      new VariableInfo("factorDespachoVar", "java.lang.String", true,
                       VariableInfo.NESTED),
      new VariableInfo("estadoVar", "java.lang.String", true,
                       VariableInfo.NESTED),
      new VariableInfo("idSeqVar", "java.lang.String", true,
                       VariableInfo.NESTED),
      new VariableInfo("referenciaVar", "java.lang.String", true,
                       VariableInfo.NESTED),
      new VariableInfo("nombreCategoriaVar", "java.lang.String", true,
                       VariableInfo.NESTED),
      new VariableInfo("nombreMarcaVar", "java.lang.String", true,
                       VariableInfo.NESTED),
      new VariableInfo("vrGeneralDf0Var", "java.lang.String", true,
                       VariableInfo.NESTED),
      new VariableInfo("vrCostoDf2Var", "java.lang.String", true,
                       VariableInfo.NESTED),
      new VariableInfo("existenciaDf2Var", "java.lang.String", true,
                                    VariableInfo.NESTED),
      new VariableInfo("vrCostoINDDf2Var", "java.lang.String", true,
                                    VariableInfo.NESTED),
    };
  }
}