package com.solucionesweb.tags;

import javax.servlet.jsp.tagext.*;

public class ListaResurtidoDetalleTxTagExtraInfo extends TagExtraInfo {

    public VariableInfo[] getVariableInfo(TagData data) {
        return new VariableInfo[]{
                    new VariableInfo("idLocalVar", "java.lang.String", true,
                    VariableInfo.NESTED),
                    new VariableInfo("nombrePluVar", "java.lang.String", true,
                    VariableInfo.NESTED),
                    new VariableInfo("nombreMarcaVar", "java.lang.String", true,
                    VariableInfo.NESTED),
                    new VariableInfo("nombreCategoriaVar", "java.lang.String", true,
                    VariableInfo.NESTED),
                    new VariableInfo("idTipoOrdenVar", "java.lang.String", true,
                    VariableInfo.NESTED),
                    new VariableInfo("idOrdenVar", "java.lang.String", true,
                    VariableInfo.NESTED),
                    new VariableInfo("idPluVar", "java.lang.String", true,
                    VariableInfo.NESTED),
                    new VariableInfo("porcentajeIvaVar", "java.lang.String", true,
                    VariableInfo.NESTED),
                    new VariableInfo("vrCostoVar", "java.lang.String", true,
                    VariableInfo.NESTED),
                    new VariableInfo("vrCostoNegociadoVar", "java.lang.String", true,
                    VariableInfo.NESTED),
                    new VariableInfo("idLogVar", "java.lang.String", true,
                    VariableInfo.NESTED),
                    new VariableInfo("cantidadPedidoVar", "java.lang.String", true,
                    VariableInfo.NESTED),
                    new VariableInfo("vrCostoPedidoVar", "java.lang.String", true,
                    VariableInfo.NESTED),
                    new VariableInfo("cantidadDf2Var", "java.lang.String", true,
                    VariableInfo.NESTED),
                    new VariableInfo("cantidadAjusteVar", "java.lang.String", true,
                    VariableInfo.NESTED),
                    new VariableInfo("cantidadVar", "java.lang.String", true,
                    VariableInfo.NESTED),
                    new VariableInfo("vrCostoPedidoDf0Var", "java.lang.String", true,
                    VariableInfo.NESTED),
                    new VariableInfo("vrCostoResurtidoVar", "java.lang.String", true,
                    VariableInfo.NESTED),
                    new VariableInfo("vrCostoResurtidoDf0Var", "java.lang.String", true,
                    VariableInfo.NESTED),
                    new VariableInfo("vrCostoResurtidoSf0Var", "java.lang.String", true,
                    VariableInfo.NESTED),
                    new VariableInfo("vrIvaResurtidoSf0Var", "java.lang.String", true,
                    VariableInfo.NESTED),
                    new VariableInfo("vrImpoconsumoSf0Var", "java.lang.String", true,
                    VariableInfo.NESTED),
                    new VariableInfo("vrCostoINDVar", "java.lang.String", true,
                    VariableInfo.NESTED),
                    new VariableInfo("xvrCostoINDVar", "java.lang.String", true,
                    VariableInfo.NESTED),
                    new VariableInfo("xvrCostoVar", "java.lang.String", true,
                    VariableInfo.NESTED),
                    new VariableInfo("existenciaVar", "java.lang.String", true,
                    VariableInfo.NESTED),
                    new VariableInfo("vrCostoResurtidoTotalDf0Var", "java.lang.String", true,
                    VariableInfo.NESTED),};
    }
}
